# Generated by Django 3.2.9 on 2021-11-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
